version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: resume_postgres
    env_file:
      - ./app/.env # Reading from .env file based in /app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - resume_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: resume_app
    env_file:
      - ./app/.env # Reading from .env file based in /app
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - resume_network
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:

networks:
  resume_network:
    driver: bridge