{{- if .Values.traefik.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: {{ .Values.global.namespace }}
data:
  traefik.yml: |
    api:
      dashboard: true
      insecure: true
    
    log:
      level: INFO
      filePath: "/var/log/traefik/traefik.log"
    
    accessLog:
      filePath: "/var/log/traefik/access.log"
      bufferingSize: 100
    
    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        address: ":443"
    
    certificatesResolvers:
      myresolver:
        acme:
          email: "admin@{{ .Values.global.domain }}"
          storage: "/letsencrypt/acme.json"
          httpChallenge:
            entryPoint: "web"
    
    providers:
      kubernetesCRD:
        enabled: true
{{- end }}