apiVersion: v1
kind: Service
metadata:
  name: resume-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: resume-frontend
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendPort }}
