{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-review-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resume-frontend
                port:
                  number: {{ .Values.service.frontendPort }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: resume-backend
                port:
                  number: {{ .Values.service.backendPort }}
{{- end }}
