{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.metricbeat.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metricbeat
  namespace: {{ .Values.global.namespace }}
  labels:
    app: metricbeat
spec:
  selector:
    matchLabels:
      app: metricbeat
  template:
    metadata:
      labels:
        app: metricbeat
    spec:
      serviceAccountName: metricbeat
      hostNetwork: true
      containers:
      - name: metricbeat
        image: {{ .Values.monitoring.metricbeat.image }}
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
          "-system.hostfs=/hostfs"
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: metricbeat-config
          mountPath: /etc/metricbeat.yml
          subPath: metricbeat.yml
        - name: procfs
          mountPath: /hostfs/proc
          readOnly: true
        - name: sysfs
          mountPath: /hostfs/sys
          readOnly: true
        - name: rootfs
          mountPath: /hostfs
          readOnly: true
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
        securityContext:
          runAsUser: 0
      volumes:
      - name: metricbeat-config
        configMap:
          name: metricbeat-config
      - name: procfs
        hostPath:
          path: /proc
      - name: sysfs
        hostPath:
          path: /sys
      - name: rootfs
        hostPath:
          path: /
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-config
  namespace: {{ .Values.global.namespace }}
data:
  metricbeat.yml: |
    metricbeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false

    metricbeat.modules:
    - module: system
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        - socket_summary
      enabled: true
      period: 10s
      processes: ['.*']
      cpu.metrics: [percentages, normalized_percentages]
      core.metrics: [percentages]

    output.logstash:
      hosts: ["logstash:5044"]

    processors:
      - add_cloud_metadata: ~
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~

    logging.level: info
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/stats
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}