apiVersion: v2
name: resume-review
description: Resume Review Application with FastAPI Backend and Flet Frontend
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.1.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled