"""Interfaces the services depend on. Implementations live in adapters/."""

from datetime import datetime
from typing import Iterable, Iterator, Optional, Protocol

from app.internal.entities import IssuedToken, Resume, Role, TokenClaims, TokenType, User


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_username(self, username: str) -> Optional[User]: ...
    def exists_username_or_email(self, username: str, email: str) -> bool: ...
    def get_by_username_or_email(self, username: str, email: str) -> Optional[User]: ...
    def add(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...
    def list_users(
        self,
        skip: int,
        limit: int,
        role: Optional[Role] = None,
        search: Optional[str] = None,
    ) -> list[User]: ...
    def count(self) -> int: ...
    def count_by_role(self) -> dict[Role, int]: ...


class ResumeRepository(Protocol):
    def add(self, resume: Resume) -> Resume: ...
    def get(self, resume_id: int) -> Optional[Resume]: ...
    def list_by_user(self, user_id: int) -> list[Resume]: ...
    def list_with_owner(self, skip: int, limit: int) -> list[tuple[Resume, User]]: ...
    def delete(self, resume_id: int) -> None: ...
    def count(self) -> int: ...


class RevokedTokenRepository(Protocol):
    def revoke(self, claims: TokenClaims) -> bool:
        """Revoke by jti. Idempotent: returns False if it was already revoked."""
        ...

    def is_revoked(self, jti: str) -> bool: ...
    def purge_expired(self, now: datetime) -> int: ...


class FileStorage(Protocol):
    def save(self, chunks: Iterable[bytes]) -> tuple[str, int]:
        """Persist the stream; returns (storage_key, size). Partial data is removed on error."""
        ...

    def exists(self, key: str) -> bool: ...
    def iter_chunks(self, key: str) -> Iterator[bytes]: ...
    def delete(self, key: str) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue(self, user_id: int, token_type: TokenType, ttl_seconds: int) -> IssuedToken: ...

    def decode(self, token: str) -> TokenClaims:
        """Validate signature and expiry; raises Unauthorized otherwise."""
        ...


__all__ = [
    "FileStorage",
    "PasswordHasher",
    "ResumeRepository",
    "RevokedTokenRepository",
    "TokenIssuer",
    "UserRepository",
]
