apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-frontend
  labels:
    app: resume-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-frontend
  template:
    metadata:
      labels:
        app: resume-frontend
    spec:
      containers:
        - name: frontend
          image: "sepehrmdn/resume_review/frontend:latest"
          ports:
            - containerPort: 8550
