apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200  # Elasticsearch address
    database: "[metricbeat-]YYYY.MM.DD"
    jsonData:
      esVersion: "7.0.0"
      timeField: "@timestamp"
      interval: "Daily"
      timeInterval: "1m"