name: Flet App CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      working-directory: ./frontend
      run: |
        docker build -f Dockerfile.frontend -t frontend:latest .
#        docker build -f Dockerfile.frontend -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest . # Uncomment if registery excists


    # - name: Push Docker image to Docker Hub
    #   working-directory: ./frontend
    #   run: |
    #     docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    # - name: Deploy to remote host via SSH
    #   uses: appleboy/ssh-action@v0.1.10
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USER }}
    #     password: ${{ secrets.SSH_PASS }}
    #     port: ${{ secrets.SSH_PORT }}
    #     script: |
    #       cd /app/
    #       docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
    #       docker stop frontend || true
    #       docker rm frontend || true
    #       docker compose up -d --force-recreate frontend:latest
